"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import RightSideDrawer from "@/components/universal-designs/drawer/RightSideDrawer";
import Popup from "@/components/universal-designs/popup/Popup";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {" "}
                <QueryClientProvider client={queryClient}>
                    <ReduxProvider>
                        {children}
                        <Popup />
                        <RightSideDrawer />
                    </ReduxProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
